# #formula of (a**m)/(a**n)
a=float(input("enter the val of a:"))
m=float(input("enter the val of m:"))
n=float(input("enter the val of n:"))
b=(a**m)/(a**n)
print(f"\t\t enter the values of {a}{m}{n}={b}")

# a=float(input("enter the val of a:"))
# m=float(input("enter the val of m:"))
# n=float(input("enter the val of n:"))
# b=a**(m-n)
# print("\t\t enter the values of {}{}{}={}".format(a,m,n,b))